# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish release on GitHub

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Prepare env vars"
        if: ${{ github.event.inputs.version != null }}
        run: echo "RELEASE_NAME = ${{github.event.inputs.version}}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            forge/build/libs/*[0-9]+.[0-9]+.[0-9]+.jar
            fabric/build/libs/*[0-9]+.[0-9]+.[0-9]+.jar
